# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lD0B-ocKCECJtiVrtVwN2ncRkpTqSXQ-
"""

!pip install streamlit
!pip install plotly

import streamlit as st
import pandas as pd
import plotly.express as px

# Charger le dataset
data = pd.read_csv('understat.com.csv')

# Titre de l'application
st.title("Statistiques de Football Interactives")

# Filtrage des données par équipe
teams = data['team'].unique()
selected_team = st.selectbox("Sélectionnez une équipe :", options=teams)

filtered_data = data[data['team'] == selected_team]

# Graphique 1 : Points réels vs Points attendus
st.subheader("Points réels vs Points attendus")
fig_pts_xpts = px.scatter(
    data,
    x="xpts",
    y="pts",
    color="team",
    hover_name="team",
    title="Points réels vs Points attendus",
    labels={"xpts": "Points attendus (xPTS)", "pts": "Points réels (PTS)"},
)
st.plotly_chart(fig_pts_xpts)

# Graphique 2 : Buts marqués vs Buts attendus
st.subheader("Buts marqués vs Buts attendus")
fig_scored_xG = px.scatter(
    data,
    x="xG",
    y="scored",
    color="team",
    hover_name="team",
    title="Buts marqués vs Buts attendus",
    labels={"xG": "Buts attendus (xG)", "scored": "Buts marqués"},
)
st.plotly_chart(fig_scored_xG)

# Graphique 3 : Heatmap des coefficients défensifs/offensifs
st.subheader("Heatmap des coefficients défensifs et offensifs")
fig_ppda_oppda = px.density_heatmap(
    data,
    x="ppda_coef",
    y="oppda_coef",
    z="pts",
    color_continuous_scale="Viridis",
    title="PPDA Coefficient vs OPPDA Coefficient",
    labels={"ppda_coef": "Coefficient PPDA", "oppda_coef": "Coefficient OPPDA"},
)
st.plotly_chart(fig_ppda_oppda)