# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lD0B-ocKCECJtiVrtVwN2ncRkpTqSXQ-
"""

import streamlit as st
import pandas as pd
import plotly.express as px

# Charger le dataset
data = pd.read_csv('understat.com.csv')

import streamlit as st
import pandas as pd
import plotly.express as px

# Charger les données
data = pd.read_csv('understat.com.csv')

# Titre de l'application
st.title("Évolution des Points des Équipes par Ligue")

# Filtrer les données par ligue
leagues = data['league'].unique()
selected_league = st.selectbox("Sélectionnez une ligue :", options=leagues)

filtered_data = data[data['league'] == selected_league]

# Animation des points par année
st.subheader(f"Évolution des Points pour {selected_league}")
fig_animation = px.scatter(
    filtered_data,
    x="position",  # Classement des équipes
    y="pts",       # Points en fin de saison
    animation_frame="year",  # Année
    size="pts",    # Taille du point proportionnelle aux points
    color="team",  # Couleur par équipe
    hover_name="team",
    title=f"Évolution des Points en {selected_league}",
    labels={
        "year": "Année",
        "pts": "Points",
        "position": "Position (Classement)"
    },
    template="plotly_dark"
)
fig_animation.update_layout(yaxis=dict(title="Points"), xaxis=dict(title="Classement"))

st.plotly_chart(fig_animation)