# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lD0B-ocKCECJtiVrtVwN2ncRkpTqSXQ-
"""

import streamlit as st
import pandas as pd
import plotly.express as px

# Charger le dataset
data = pd.read_csv('understat.com.csv')

# Charger le dataset
data = pd.read_csv('understat.com.csv')

# Ajouter l'URL de base pour les logos
GITHUB_BASE_URL = "https://raw.githubusercontent.com/Rako75/streamlitfoot/main/Premier%20League/"

# Ajouter une colonne avec les URLs des logos
data['logo_url'] = data['team'].apply(lambda x: f"{GITHUB_BASE_URL}{x.replace(' ', '_')}.png")

# Titre de l'application
st.title("Évolution des Points des Équipes par Ligue avec Logos")

# Filtrer les données par ligue
leagues = data['league'].unique()  # Suppose que cette colonne contient les noms des ligues
selected_league = st.selectbox("Sélectionnez une ligue :", options=leagues)

# Filtrer les données en fonction de la ligue sélectionnée
filtered_data = data[data['league'] == selected_league]

# Animation des points par année avec logos
st.subheader(f"Évolution des Points pour {selected_league}")

# Créer un graphique interactif avec animation
fig_animation = px.scatter(
    filtered_data,
    x="position",       # Classement des équipes
    y="pts",            # Points en fin de saison
    animation_frame="year",  # Année
    size="pts",         # Taille des points proportionnelle aux points
    color="team",       # Couleur par équipe
    hover_name="team",  # Nom affiché au survol
    title=f"Évolution des Points en {selected_league}",
    labels={
        "Unnamed: 1": "Année",
        "pts": "Points",
        "position": "Position (Classement)"
    },
    template="plotly_dark"
)

# Ajouter les logos au graphique
for i, row in filtered_data.iterrows():
    fig_animation.add_layout_image(
        dict(
            source=row['logo_url'],  # URL du logo
            x=row['position'],       # Position sur l'axe x
            y=row['pts'],            # Position sur l'axe y
            xref="x",
            yref="y",
            sizex=0.5,               # Taille du logo
            sizey=0.5,
            xanchor="center",
            yanchor="middle"
        )
    )

# Afficher le graphique dans Streamlit
st.plotly_chart(fig_animation)