# -*- coding: utf-8 -*-
"""chatbot_ballondor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kZW8P3P-1ICdawztOa2j-dmuNrID-zLT
"""

#pip install python-dotenv streamlit openai pandas

import os
from dotenv import load_dotenv

# Charger le fichier .env
load_dotenv("config.env")

# Accéder à la clé API
openai_api_key = os.getenv("OPENAI_API_KEY")

import streamlit as st
import pandas as pd
import openai

# 1. Configuration de l'API OpenAI
openai.api_key = "YOUR_API_KEY"  # Remplacez par votre clé API OpenAI

# 2. Chargement des données
@st.cache_data
def load_data():
    return pd.read_csv('Ballondor2024.csv')  # Remplacez par le nom de votre fichier CSV

# 3. Génération de réponse avec OpenAI GPT
def generate_gpt_response(prompt):
    try:
        response = openai.ChatCompletion.create(
            model="gpt-4",  # Utiliser GPT-3.5 si GPT-4 n'est pas disponible
            messages=[
                {"role": "system", "content": "Tu es un chatbot expert sur le Ballon d'Or 2024, avec des données précises sur les joueurs, leurs performances et statistiques."},
                {"role": "user", "content": prompt}
            ],
            max_tokens=250,
            temperature=0.7
        )
        return response['choices'][0]['message']['content']
    except Exception as e:
        return f"Une erreur est survenue : {str(e)}"

# 4. Extraire les statistiques spécifiques des joueurs
def get_player_stats(player_name, data):
    player_data = data[data['player'].str.contains(player_name, case=False, na=False)]
    if not player_data.empty:
        stats = player_data.iloc[0]
        return (f"Voici les statistiques de {stats['player']} :\n"
                f"- **Équipe** : {stats['team']}\n"
                f"- **Buts marqués** : {stats['Performance-Gls']}\n"
                f"- **Passes décisives** : {stats['Performance-Ast']}\n"
                f"- **xG Attendu** : {stats['Expected-xG']}\n"
                f"- **Minutes jouées** : {stats['Playing Time-Min']}")
    return "Je n'ai pas trouvé les statistiques pour ce joueur."

# 5. Combiner réponse GPT et données structurées
def chatbot_response(question, data):
    # Vérifier si le joueur est mentionné dans la question
    for player in data['player']:
        if player.lower() in question.lower():
            stats = get_player_stats(player, data)
            gpt_prompt = f"Réponds naturellement à la question : '{question}'. Voici les statistiques de {player} : {stats}"
            return generate_gpt_response(gpt_prompt)

    # Si pas de joueur spécifique, poser directement la question au modèle GPT
    gpt_prompt = f"Réponds naturellement à la question suivante sur le Ballon d'Or 2024 : '{question}'."
    return generate_gpt_response(gpt_prompt)

# 6. Interface Streamlit
st.title("🏆 ChatBot Ballon d'Or 2024")
st.write("Discutez naturellement avec moi pour obtenir des informations sur le Ballon d'Or, les joueurs et leurs statistiques !")

# Chargement des données
data = load_data()

# Entrée utilisateur
user_input = st.text_input("💬 Posez-moi une question ici (ex: Qui a marqué le plus de buts ?)")

if user_input:
    st.write("⏳ **Je réfléchis...**")
    response = chatbot_response(user_input, data)
    st.write(response)

    # Ajouter une vidéo si un joueur est identifié
    for player in data['player']:
        if player.lower() in user_input.lower():
            video_url = data.loc[data['player'].str.contains(player, case=False), 'URL'].iloc[0]
            if pd.notna(video_url):
                st.video(video_url)
                st.write(f"🎥 Moments forts de {player} : [Regarder ici]({video_url})")
            break