# -*- coding: utf-8 -*-
"""chatbot_ballondor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kZW8P3P-1ICdawztOa2j-dmuNrID-zLT
"""

import streamlit as st
import pandas as pd
from transformers import pipeline

# Charger les données filtrées depuis un fichier CSV
@st.cache_data
def load_data():
    data = pd.read_csv('Ballondor2024.csv')  # Remplacez par le chemin de votre fichier CSV
    return data

# Charger le modèle de langage
@st.cache_resource
def load_model():
    return pipeline("text-generation", model="EleutherAI/gpt-neo-125M")

# Récupérer l'URL des moments forts d'un joueur
def get_highlight_url(player_name, data):
    player_data = data[data['player'].str.contains(player_name, case=False, na=False)]
    if not player_data.empty:
        return player_data['URL'].values[0]  # Retourne la première URL trouvée
    else:
        return None

# Charger les données et le modèle
data = load_data()
model = load_model()

# Interface Streamlit
st.title("🏆 Chatbot Ballon d'Or 2024")
st.write("Posez des questions sur les nominés, découvrez leurs performances et regardez leurs meilleurs moments !")

# **Section 1 : Question générale sur le Ballon d'Or**
st.header("❓ Poser une question générale")
question = st.text_input("Entrez votre question :")

if question:
    # Générer une réponse avec le modèle
    with st.spinner("Le chatbot réfléchit..."):
        response = model(question, max_length=50)[0]['generated_text']
    st.write("💬 Réponse du Chatbot :")
    st.write(response)

# **Section 2 : Recherche des moments forts d'un joueur**
st.header("🎥 Moments forts d'un joueur")
player_name = st.text_input("Recherchez un joueur par son nom :")

if player_name:
    highlight_url = get_highlight_url(player_name, data)
    if highlight_url:
        st.video(highlight_url)  # Intégrer la vidéo directement
        st.write(f"Regardez les moments forts de **{player_name}** ici : [Lien direct]({highlight_url})")
    else:
        st.write("❌ Aucune vidéo trouvée pour ce joueur. Vérifiez l'orthographe ou essayez un autre nom.")

# **Section 3 : Explorateur de joueurs**
st.header("📊 Explorateur des statistiques")
st.write("Découvrez les statistiques des joueurs nominés au Ballon d’Or 2024.")

# Sélection d'un joueur dans un menu déroulant
player_list = data['player'].unique()
selected_player = st.selectbox("Sélectionnez un joueur :", player_list)

if selected_player:
    player_stats = data[data['player'] == selected_player].iloc[0]  # Récupère les stats du joueur sélectionné
    st.subheader(f"Statistiques de {selected_player}")
    st.write("🏟️ Équipe :", player_stats['team'])
    st.write("🌍 Nation :", player_stats['nation'])
    st.write("⚽ Buts :", player_stats['Performance-Gls'])
    st.write("🎯 Passes décisives :", player_stats['Performance-Ast'])
    st.write("📊 xG attendu :", player_stats['Expected-xG'])
    st.write("🚫 Cartons jaunes :", player_stats['Performance-CrdY'])
    st.write("🟥 Cartons rouges :", player_stats['Performance-CrdR'])

    # Affichage vidéo, si disponible
    if pd.notna(player_stats['URL']):
        st.video(player_stats['URL'])
        st.write(f"🎥 Moments forts de **{selected_player}** : [Lien direct]({player_stats['URL']})")

# **Footer**
st.write("---")
st.write("⚡ Chatbot réalisé avec Streamlit et Hugging Face Transformers. Données issues du fichier `Ballondor2024.csv`.")